# default: &default
#   adapter: jdbcpostgresql
#   encoding: unicode
#   pool: 4
#   username: root
#   password: root
#   host: localhost

# development: &development
#   <<: *default
#   database: sr_development

# production: &production
#   <<: *default
#   database: sr_production

# mysql_data_source: &pii
#   adapter: mysql2
#   hostname: localhost
#   port: 3306
#   socket: /tmp/mysqld.sock
#   database: sr_development
#   username: root
#   password: root


default: &default
  adapter: postgresql
  database: sr_development
  username: postgres
  password: password
  host: localhost
  reconnect: false
  encoding: utf8

development:
  <<: *default

production:
  <<: *default
  database: sr_production